import CanvasModel from "@/components/canvas/CanvasModel";
import Customizer from "@/components/customizer/Customizer";
import Home from "@/components/home/Home";
import Head from "next/head";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Main() {
  return (
    <>
      <Head>
        <title>3D RENDERED WEBSITE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="app transition-all ease-in duration-5000">
        <Home />
        <CanvasModel />
        <Customizer />
      </main>
    </>
  );
}
